// Auto-generated Fexi Thunks for d3d9.dll
// Do not edit this file directly.

#include "macwi/thunk.h"

extern uint64_t host_Direct3DCreate9(EMU_CONTEXT* ctx, uint32_t SDKVersion);

static void thunk_Direct3DCreate9(EMU_CONTEXT* ctx) {
    uint32_t SDKVersion;
    macwi_thunk_read_param_32(ctx, 0, (uint32_t*)&SDKVersion);
    uint64_t ret = host_Direct3DCreate9(ctx, SDKVersion);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 1);
}

void fexi_register_d3d9(void) {
    macwi_thunk_register_api("d3d9.dll", "Direct3DCreate9", thunk_Direct3DCreate9, 1);
}