// Auto-generated Fexi Thunks for kernel32.dll
// Do not edit this file directly.

#include "macwi/thunk.h"

extern uint64_t host_DeleteFileA(EMU_CONTEXT* ctx, uint64_t lpFileName);
extern uint64_t host_GetFileAttributesA(EMU_CONTEXT* ctx, uint64_t lpFileName);
extern uint64_t host_SetFileAttributesA(EMU_CONTEXT* ctx, uint64_t lpFileName, uint64_t dwFileAttributes);
extern uint64_t host_GetSystemDirectoryA(EMU_CONTEXT* ctx, uint64_t lpBuffer, uint64_t uSize);
extern uint64_t host_GetWindowsDirectoryA(EMU_CONTEXT* ctx, uint64_t lpBuffer, uint64_t uSize);

static void thunk_DeleteFileA(EMU_CONTEXT* ctx) {
    uint64_t lpFileName;
    macwi_thunk_read_param_64(ctx, 0, (uint64_t*)&lpFileName);
    uint64_t ret = host_DeleteFileA(ctx, lpFileName);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 1);
}

static void thunk_GetFileAttributesA(EMU_CONTEXT* ctx) {
    uint64_t lpFileName;
    macwi_thunk_read_param_64(ctx, 0, (uint64_t*)&lpFileName);
    uint64_t ret = host_GetFileAttributesA(ctx, lpFileName);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 1);
}

static void thunk_SetFileAttributesA(EMU_CONTEXT* ctx) {
    uint64_t lpFileName;
    macwi_thunk_read_param_64(ctx, 0, (uint64_t*)&lpFileName);
    uint64_t dwFileAttributes;
    macwi_thunk_read_param_64(ctx, 1, (uint64_t*)&dwFileAttributes);
    uint64_t ret = host_SetFileAttributesA(ctx, lpFileName, dwFileAttributes);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 2);
}

static void thunk_GetSystemDirectoryA(EMU_CONTEXT* ctx) {
    uint64_t lpBuffer;
    macwi_thunk_read_param_64(ctx, 0, (uint64_t*)&lpBuffer);
    uint64_t uSize;
    macwi_thunk_read_param_64(ctx, 1, (uint64_t*)&uSize);
    uint64_t ret = host_GetSystemDirectoryA(ctx, lpBuffer, uSize);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 2);
}

static void thunk_GetWindowsDirectoryA(EMU_CONTEXT* ctx) {
    uint64_t lpBuffer;
    macwi_thunk_read_param_64(ctx, 0, (uint64_t*)&lpBuffer);
    uint64_t uSize;
    macwi_thunk_read_param_64(ctx, 1, (uint64_t*)&uSize);
    uint64_t ret = host_GetWindowsDirectoryA(ctx, lpBuffer, uSize);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 2);
}

void fexi_register_kernel32(void) {
    macwi_thunk_register_api("kernel32.dll", "DeleteFileA", thunk_DeleteFileA, 1);
    macwi_thunk_register_api("kernel32.dll", "GetFileAttributesA", thunk_GetFileAttributesA, 1);
    macwi_thunk_register_api("kernel32.dll", "SetFileAttributesA", thunk_SetFileAttributesA, 2);
    macwi_thunk_register_api("kernel32.dll", "GetSystemDirectoryA", thunk_GetSystemDirectoryA, 2);
    macwi_thunk_register_api("kernel32.dll", "GetWindowsDirectoryA", thunk_GetWindowsDirectoryA, 2);
}