// Auto-generated Fexi Thunks for user32.dll
// Do not edit this file directly.

#include "macwi/thunk.h"

extern uint64_t host_ShowWindow(EMU_CONTEXT* ctx, uint64_t hWnd, uint64_t nCmdShow);
extern uint64_t host_UpdateWindow(EMU_CONTEXT* ctx, uint64_t hWnd);

static void thunk_ShowWindow(EMU_CONTEXT* ctx) {
    uint64_t hWnd;
    macwi_thunk_read_param_64(ctx, 0, (uint64_t*)&hWnd);
    uint64_t nCmdShow;
    macwi_thunk_read_param_64(ctx, 1, (uint64_t*)&nCmdShow);
    uint64_t ret = host_ShowWindow(ctx, hWnd, nCmdShow);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 2);
}

static void thunk_UpdateWindow(EMU_CONTEXT* ctx) {
    uint64_t hWnd;
    macwi_thunk_read_param_64(ctx, 0, (uint64_t*)&hWnd);
    uint64_t ret = host_UpdateWindow(ctx, hWnd);
    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);
    macwi_thunk_stdcall_return(ctx, 1);
}

void fexi_register_user32(void) {
    macwi_thunk_register_api("user32.dll", "ShowWindow", thunk_ShowWindow, 2);
    macwi_thunk_register_api("user32.dll", "UpdateWindow", thunk_UpdateWindow, 1);
}