#!/usr/bin/env python3
import json
import sys
import os

def generate_thunks(json_path):
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    dll_name = data.get("dll_name", "unknown.dll")
    apis = data.get("apis", [])
    
    out_lines = []
    out_lines.append(f"// Auto-generated Fexi Thunks for {dll_name}")
    out_lines.append(f"// Do not edit this file directly.")
    out_lines.append("")
    out_lines.append("#include \"macwi/thunk.h\"")
    out_lines.append("")
    
    # Generate host declarations
    for api in apis:
        name = api["name"]
        ret_type = api.get("ret", "uint32_t")
        args = api.get("args", [])
        
        arg_decls = ["EMU_CONTEXT* ctx"]
        for arg in args:
            arg_decls.append(f"{arg['type']} {arg['name']}")
        
        out_lines.append(f"extern {ret_type} host_{name}({', '.join(arg_decls)});")
    out_lines.append("")
    
    # Generate thunk functions
    for api in apis:
        name = api["name"]
        ret_type = api.get("ret", "uint32_t")
        args = api.get("args", [])
        num_args = len(args)
        
        out_lines.append(f"static void thunk_{name}(EMU_CONTEXT* ctx) {{")
        
        # Read parameters
        for i, arg in enumerate(args):
            arg_name = arg["name"]
            arg_type = arg["type"]
            out_lines.append(f"    {arg_type} {arg_name};")
            if arg_type == "uint64_t":
                out_lines.append(f"    macwi_thunk_read_param_64(ctx, {i}, (uint64_t*)&{arg_name});")
            else:
                out_lines.append(f"    macwi_thunk_read_param_32(ctx, {i}, (uint32_t*)&{arg_name});")
        
        # Call host function
        call_args = ["ctx"] + [arg["name"] for arg in args]
        call_str = f"host_{name}({', '.join(call_args)})"
        
        if ret_type == "void":
            out_lines.append(f"    {call_str};")
        else:
            out_lines.append(f"    {ret_type} ret = {call_str};")
            out_lines.append(f"    macwi_emu_reg_write_64(ctx, 0, (uint64_t)ret);")
            
        out_lines.append(f"    macwi_thunk_stdcall_return(ctx, {num_args});")
        out_lines.append("}")
        out_lines.append("")
    
    # Generate registration function
    prefix = dll_name.replace(".dll", "")
    out_lines.append(f"void fexi_register_{prefix}(void) {{")
    for api in apis:
        name = api["name"]
        num_args = len(api.get("args", []))
        out_lines.append(f"    macwi_thunk_register_api(\"{dll_name}\", \"{name}\", thunk_{name}, {num_args});")
    out_lines.append("}")
    
    return "\n".join(out_lines)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: fexi_gen.py <input.json> <output.c>")
        sys.exit(1)
        
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    
    content = generate_thunks(input_path)
    with open(output_path, 'w') as f:
        f.write(content)
    print(f"Generated {output_path}")
