#!/usr/bin/env python3
import xml.etree.ElementTree as ET
import sys
import os

def parse_vk_xml(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()

    commands = {}
    
    for cmd in root.findall('.//commands/command'):
        if 'alias' in cmd.attrib:
            continue
            
        proto = cmd.find('proto')
        if proto is None:
            continue
            
        name_elem = proto.find('name')
        if name_elem is None:
            continue
            
        func_name = name_elem.text
        if func_name in commands:
            continue # skip duplicates
        
        params = []
        for param in cmd.findall('param'):
            ptype = param.find('type')
            pname = param.find('name')
            if ptype is not None and pname is not None:
                type_str = "".join(param.itertext()).replace(pname.text, "").strip()
                params.append((type_str, pname.text))
                
        commands[func_name] = {
            'name': func_name,
            'params': params
        }
        
    return list(commands.values())

def generate_c_code(commands, output_path):
    with open(output_path, 'w') as f:
        f.write("// Auto-generated by generate_vulkan_thunks.py\n")
        f.write("#include <macwi/emu.h>\n")
        f.write("#include <macwi/thunk.h>\n")
        f.write("#include <macwi/moltenvk_loader.h>\n")
        f.write("#include <stdio.h>\n\n")
        
        # Generate the thunk callbacks
        for cmd in commands:
            func_name = cmd['name']
            
            f.write(f"static void macwi_vk_{func_name}_thunk(EMU_CONTEXT* ctx) {{\n")
            f.write(f"    // {func_name} has {len(cmd['params'])} parameters\n")
            f.write(f"    fprintf(stderr, \"[macwi:vulkan] {func_name} called!\\n\");\n")
            f.write(f"    macwi_emu_reg_write_64(ctx, 0, 0);\n")
            f.write(f"    macwi_thunk_stdcall_return(ctx, {len(cmd['params'])});\n")
            f.write("}\n\n")
            
        # Generate the registration function
        f.write("static void macwi_vulkan_register_all_thunks(EMU_CONTEXT* ctx) {\n")
        for cmd in commands:
            func_name = cmd['name']
            num_args = len(cmd['params'])
            f.write(f"    macwi_thunk_register_api(\"vulkan-1.dll\", \"{func_name}\", macwi_vk_{func_name}_thunk, {num_args});\n")
        f.write("}\n")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 generate_vulkan_thunks.py <vk.xml path> <output.inc path>")
        sys.exit(1)
        
    xml_path = sys.argv[1]
    out_path = sys.argv[2]
    
    commands = parse_vk_xml(xml_path)
    print(f"Parsed {len(commands)} unique Vulkan commands.")
    generate_c_code(commands, out_path)
    print(f"Generated {out_path}")
